USE ShopDb

--SELECT

SELECT * FROM CUSTOMERS

SELECT CustomerId, FirstName, LastName FROM CUSTOMERS

--WHERE

SELECT * FROM CUSTOMERS WHERE CustomerId = 2

SELECT * FROM CUSTOMERS WHERE City != 'Los Angeles'

--NULL Values

SELECT * FROM CUSTOMERS WHERE Phone IS NULL

SELECT * FROM CUSTOMERS WHERE Phone IS NOT NULL

--ORDER BY

SELECT * FROM CUSTOMERS ORDER BY FirstName

SELECT * FROM CUSTOMERS ORDER BY FirstName DESC

SELECT * FROM CUSTOMERS ORDER BY City, FirstName

SELECT * FROM CUSTOMERS ORDER BY FirstName ASC , LastName DESC


--DISTINCT

SELECT DISTINCT City FROM CUSTOMERS

--TOP Clause

SELECT TOP 3 * FROM CUSTOMERS

SELECT TOP 50 PERCENT * FROM CUSTOMERS

--Operators

SELECT * FROM CUSTOMERS WHERE City = 'Chicago'
SELECT * FROM CUSTOMERS WHERE City <> 'Chicago'

SELECT * FROM CUSTOMERS WHERE Age > 30
SELECT * FROM CUSTOMERS WHERE Age <= 25

--Alias

SELECT FirstName AS 'First Name' FROM CUSTOMERS

SELECT FirstName + ' ' + LastName AS 'Name' FROM CUSTOMERS

SELECT FirstName + CAST(Age AS VARCHAR(10)) AS 'CustomerCode' FROM CUSTOMERS

--AND, OR and NOT Operators

SELECT * FROM CUSTOMERS WHERE City = 'Chicago' AND Age >= 30

SELECT * FROM CUSTOMERS WHERE AGE >= 25 OR City = 'New York'
SELECT * FROM CUSTOMERS WHERE City = 'New York' OR City = 'Chicago'

SELECT * FROM CUSTOMERS WHERE NOT City = 'Chicago'
SELECT * FROM CUSTOMERS WHERE NOT Address='Chicago' AND NOT Address='New York'

--IN Operator

SELECT * FROM CUSTOMERS WHERE AGE IN (25, 30)
SELECT * FROM CUSTOMERS WHERE City IN ('New York', 'Houston', 'Phoenix')
SELECT * FROM CUSTOMERS WHERE Address NOT IN ('New York', 'Chicago')

--BETWEEN Operator
SELECT * FROM Customers WHERE DateOfBirth BETWEEN '1990-01-01' AND '2000-12-31'
SELECT * FROM CUSTOMERS WHERE DATEDIFF(year, DateOfBirth, GETDATE()) BETWEEN 25 AND 30

SELECT * FROM CUSTOMERS WHERE AGE NOT BETWEEN 25 AND 30
SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 25 AND 30 AND CustomerId NOT IN (1,2,3)

--LIKE Operator

SELECT * FROM CUSTOMERS WHERE FirstName LIKE 'Em%'
SELECT * FROM CUSTOMERS WHERE FirstName LIKE '%a%'
SELECT * FROM CUSTOMERS WHERE FirstName LIKE '_o%'
SELECT * FROM CUSTOMERS WHERE Phone LIKE '555%'
SELECT * FROM CUSTOMERS WHERE FirstName LIKE 'Em%' AND AGE >= 30

--GROUP BY

SELECT City, COUNT(*) FROM CUSTOMER GROUP BY City

SELECT City, COUNT(*) FROM CUSTOMER GROUP BY City
ORDER BY COUNT(CustomerID) DESC

SELECT DepartmentId, MAX(Salary) FROM EMPLOYEE 
GROUP BY DepartmentId 
ORDER BY MAX(Salary) DESC

SELECT City, DepartmentId, MAX(Salary) FROM EMPLOYEE 
GROUP BY City, DepartmentId 

SELECT DepartmentId, Gender, MAX(Salary) FROM EMPLOYEE 
GROUP BY DepartmentId, Gender 


--SELECT INTO Statement

SELECT * INTO CustomersBackup FROM CUSTOMERS

SELECT * INTO CustomersHouston FROM CUSTOMERS where City = 'Houston'


--CASE Statement

SELECT FirstName,
CASE
	WHEN Salary < 50000 THEN 'Below 50000'
	WHEN Salary >= 50000 THEN 'Above 50000'
END
FROM EMPLOYEE


SELECT CustomerId, Age,
CASE
    WHEN Age > 30 THEN 'Age is greater than 30'
    WHEN Age = 30 THEN 'Age is 30'
    ELSE 'Invalid Age'
END AS AgeCheck
FROM CUSTOMERS