--Scalar subquery
	 
SELECT * FROM EMPLOYEE 
WHERE Salary = (SELECT MAX(Salary) FROM EMPLOYEE)

SELECT * FROM EMPLOYEE 
WHERE Salary < (SELECT AVG(Salary) FROM EMPLOYEE)

SELECT * FROM EMPLOYEE WHERE DepartmentId = (SELECT Id FROM DEPARTMENT WHERE Name ='HR')

INSERT INTO EMPLOYEE_BKP
SELECT * FROM EMPLOYEE WHERE Id IN (SELECT Id FROM EMPLOYEE)

INSERT INTO EMPLOYEE_BKP
SELECT Name, Age, Address, Salary FROM EMPLOYEE 
WHERE Id IN (SELECT Id FROM EMPLOYEE)

UPDATE EMPLOYEE SET SALARY = SALARY * 0.25
WHERE AGE IN (SELECT AGE FROM EMPLOYEE_BKP WHERE AGE >= 27 )


SELECT Name,Age FROM EMPLOYEE 
WHERE Salary > (SELECT AVG(Salary) + 1000 FROM EMPLOYEE)


--Multi valued Subquery

SELECT * FROM PRODUCTS
WHERE Id NOT IN (SELECT DISTINCT ProductId FROM ORDER_ITEMS)

SELECT * FROM EMPLOYEE 
WHERE Id IN (SELECT Id FROM EMPLOYEE WHERE Salary > 50000)

SELECT * FROM EMPLOYEE WHERE EmployeeId IN (SELECT Id FROM EMPLOYEE WHERE City ='Los Angeles')	  

SELECT * FROM EMPLOYEE WHERE EmployeeId NOT IN (SELECT Id FROM EMPLOYEE WHERE City ='Los Angeles')

SELECT * FROM EMPLOYEE WHERE (DepartmentId, Salary) IN 
(SELECT DepartmentId, MAX(Salary) FROM EMPLOYEE GROUP BY DepartmentId)

SELECT * FROM DEPARTMENT WHERE Id NOT IN 
(SELECT DISTINCT(DepartmentId) FROM EMPLOYEE)


--Correlated Subquery

SELECT * FROM EMPLOYEE WHERE Salary >
(SELECT AVG(Salary) FROM EMPLOYEE WHERE DepartmentId )

SELECT d.Name, 
(SELECT COUNT(*) FROM Employee e
 WHERE e.DepartmentId = d.Id
) AS TotalEmployees
FROM Department d

SELECT d.Name, 
(SELECT AVG(e.Salary) FROM Employee e WHERE e.DepartmentId = d.Id) AS AverageSalary
FROM Department d

--ANY operator

SELECT * FROM EMPLOYEE WHERE Salary < 
ANY (SELECT Salary FROM EMPLOYEE WHERE EmployeeName ='Jamal' OR EmployeeName ='Jahan')

SELECT * FROM EMPLOYEE WHERE DeptId > ANY (SELECT DeptId FROM DEPARTMENT WHERE Budget > 300000.00)

--ALL operator

SELECT * FROM EMPLOYEE WHERE Salary < 
ALL (SELECT Salary FROM EMPLOYEE WHERE EmployeeName ='Jamal' OR EmployeeName ='Jahan')

SELECT * FROM EMPLOYEE WHERE DeptId > ALL (SELECT DeptId FROM DEPARTMENT WHERE Budget > 300000.00)

--EXISTS operator

SELECT * FROM EMPLOYEE WHERE EXISTS
(SELECT DepartmentId FROM DEPARTMENT WHERE EMPLOYEE.DepartmentId = DEPARTMENT.Id AND DEPARTMENT.Id =6)


SELECT * FROM EMPLOYEE WHERE NOT EXISTS (SELECT d.Id FROM DEPARTMENT as d JOIN EMPLOYEE as e 
on (e.DepartmentId = d.Id) WHERE d.DepartmentId = 6)


