CREATE DATABASE ShopDb
USE ShopDb

--PRIMARY KEY

CREATE TABLE CUSTOMERS
(
CustomerId int IDENTITY(1,1) PRIMARY KEY,
FirstName varchar(50) NOT NULL,
LastName varchar(50) NOT NULL,
Email varchar(50) NOT NULL,
Phone varchar(12) NULL,
Age int NOT NULL,
City varchar(200)
)

--FOREIGN KEY

CREATE TABLE ORDERS
(
OrderId int IDENTITY(1,1) PRIMARY KEY,
OrderDate date NOT NULL,
CustomerId int NOT NULL FOREIGN KEY REFERENCES CUSTOMERS (CustomerId),
OrderAmount money NULL
)   

--PRIMARY KEY

ALTER TABLE CUSTOMERS
ADD PRIMARY KEY (CustomerId);

ALTER TABLE ORDERS
ADD PRIMARY KEY (OrderId);

--PRIMARY KEY On Multiple columns

ALTER TABLE CUSTOMERS
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustomerId, Email)

--DROP PRIMARY KEY Constraint

ALTER TABLE Persons
DROP CONSTRAINT PK_CustomerId;

--FOREIGN KEY

ALTER TABLE ORDERS
ADD FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS(CustomerId);

--UNIQUE 

ALTER TABLE CUSTOMERS
ADD CONSTRAINT UQ_email UNIQUE(Email)

--DROP UNIQUE Constraint

ALTER TABLE CUSTOMERS
DROP CONSTRAINT UQ_Email

--CHECK Constraint

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CK_CustomerNumber CHECK(CustomerNumber>1000)

--DEFAULT Constraint

ALTER TABLE CUSTOMERS
ADD CONSTRAINT df_City
DEFAULT 'New York' FOR City;

--DROP DEFAULT Constraint

ALTER TABLE CUSTOMERS
ALTER COLUMN City DROP DEFAULT;

--Cascading Referential Integrity Constraint

ALTER TABLE ORDERS
ADD FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS (CustomerId);
ON DELETE CASCADE 
ON UPDATE CASCADE

ALTER TABLE ORDERS
ADD FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS (CustomerId);
ON DELETE SET NULL
ON UPDATE SET NULL

-- -- --

CREATE TABLE CUSTOMERS
(
CustomerId int IDENTITY(1,1) PRIMARY KEY,
FirstName varchar(50) NOT NULL,
LastName varchar(50) NOT NULL,
Email varchar(50) NOT NULL UNIQUE,
Phone varchar(12) NULL,
Age int NOT NULL CHECK (Age >= 18),
City varchar(200) DEFAULT 'New York',
CreatedAt DATETIME DEFAULT GETDATE()
)